### ISSUE TITLE
heal command is not working in Craftbukkit 1.5.2-R1.0

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/CommandBook#216]
CMDBOOK-2300 - Reported by Beutelsack

The heal command is not working in Craftbukkit 1.5.2-R1.0.

Tested with:
Commandbook 2.3

Working with Craftbukkit 1.6.2-R0.2 Development Build #2849 !!!

Error with Craftbukkit 1.5.2-R1.0 Recommended Build #2788:

2013-08-09 11:16:42 [INFO] Beutelsack issued server command: /heal
2013-08-09 11:16:42 [SEVERE] com.sk89q.minecraft.util.commands.WrappedCommandException: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getMaxHealth()D
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:543)
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:409)
2013-08-09 11:16:42 [SEVERE] 	at com.zachsthings.libcomponents.bukkit.BukkitComponent.onCommand(BukkitComponent.java:80)
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
2013-08-09 11:16:42 [SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
2013-08-09 11:16:42 [SEVERE] 	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:971)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:889)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:846)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:115)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
2013-08-09 11:16:42 [SEVERE] 	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
2013-08-09 11:16:42 [SEVERE] Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getMaxHealth()D
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.commandbook.PlayerComponent$Commands.heal(PlayerComponent.java:148)
2013-08-09 11:16:42 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-08-09 11:16:42 [SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-08-09 11:16:42 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-08-09 11:16:42 [SEVERE] 	at java.lang.reflect.Method.invoke(Unknown Source)
2013-08-09 11:16:42 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
2013-08-09 11:16:42 [SEVERE] 	... 19 more
